### ISSUE TITLE
chapter 1.4.6.2. 

### ISSUE THREAD

**Issue by Thomas84** [modelab/grasshopper-primer#61]
chapter 1.4.6.2.: to explain the picture below the text: 

replace "In this example, we have set the i-input to 5.0 so the List Item component returns the data item associated with the 5th entry number in our list." with "In this example, we have set the i-input to 2 so the List Item component returns the data item associated with the 3rd entry number (index 2) in our list."

please check if my assumption is correct

**Comment by Thomas84** [comment]
I just discovered: the example files numbers are not matching the picture of http://grasshopperprimer.com

**Comment by gakos** [comment]
Updated text in V3.3
