### ISSUE TITLE
chapter 1.4.6.3. REVERSE LIST

### ISSUE THREAD

**Issue by Thomas84** [modelab/grasshopper-primer#62]
chapter 1.4.6.3.:
replace 

"If we input an ascending list of numbers from 0.0 to 9.0 into the Reverse List component; the output returns a descending list from 9.0 to 0.0."

with

"If we input an ascending list of numbers from 0.0 to 50.0 into the Reverse List component; the output returns a descending list from 50.0 to 0.0."

**Comment by gakos** [comment]
Thanks for the submission. Fixed in V3.3.
